name: Feature Request
description: Create a feature request
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please detail your feature request.
    validations:
      required: true
