name: Check Build
on:
  push:
      branches: ['*']
  pull_request:
      branches: ['*']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: ./gradlew build -Pmod_version="$(git describe --always --tags | cut -c2-)" --stacktrace --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          name: multiconnect-snapshot
          path: build/libs/
